In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
from pandas import Series, DataFrame
import pandas as pd

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

import sklearn

In [35]:
import requests, zipfile
import io

url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data'
res = requests.get(url).content

auto_data = pd.read_csv(io.StringIO(res.decode('utf-8')), header = None)
auto_data

     0    1            2       3      4     5   ...    20   21    22  23  24     25
0     3    ?  alfa-romero     gas    std   two  ...   9.0  111  5000  21  27  13495
1     3    ?  alfa-romero     gas    std   two  ...   9.0  111  5000  21  27  16500
2     1    ?  alfa-romero     gas    std   two  ...   9.0  154  5000  19  26  16500
3     2  164         audi     gas    std  four  ...  10.0  102  5500  24  30  13950
4     2  164         audi     gas    std  four  ...   8.0  115  5500  18  22  17450
..   ..  ...          ...     ...    ...   ...  ...   ...  ...   ...  ..  ..    ...
200  -1   95        volvo     gas    std  four  ...   9.5  114  5400  23  28  16845
201  -1   95        volvo     gas  turbo  four  ...   8.7  160  5300  19  25  19045
202  -1   95        volvo     gas    std  four  ...   8.8  134  5500  18  23  21485
203  -1   95        volvo  diesel  turbo  four  ...  23.0  106  4800  26  27  22470
204  -1   95        volvo     gas  turbo  four  ...   9.5  114  5400  19  25  22625

[205 rows x 26 columns]

In [36]:
auto_data.columns = ['sysmboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height',
                                      'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price']

In [37]:
print('자동차 데이터 형태 : {}'.format(auto_data.shape))
auto_data.head()

자동차 데이터 형태 : (205, 26)

   sysmboling normalized-losses         make  ... city-mpg highway-mpg  price
0           3                 ?  alfa-romero  ...       21          27  13495
1           3                 ?  alfa-romero  ...       21          27  16500
2           1                 ?  alfa-romero  ...       19          26  16500
3           2               164         audi  ...       24          30  13950
4           2               164         audi  ...       18          22  17450

[5 rows x 26 columns]

In [38]:
auto_data = auto_data[['price','engine-size','width']]
auto_data.isin(['?']).sum()

price          4
engine-size    0
width          0
dtype: int64

In [39]:
auto_data = auto_data.replace('?', np.nan).dropna()
print('데이터 shape :{}'.format(auto_data.shape))

데이터 shape :(201, 3)

In [40]:
print('데이터 형 확인(변환 전)\n{}\n'.format(auto_data.dtypes))

데이터 형 확인(변환 전)
price           object
engine-size      int64
width          float64
dtype: object

In [42]:
auto_data = auto_data.assign(price=pd.to_numeric(auto_data.price))
#auto_data = auto_data.assign(horsepower=pd.to_numeric(auto_data.horsepower))
print('데이터 형 확인(변환 후)\n{}'.format(auto_data.dtypes))

데이터 형 확인(변환 후)
price            int64
engine-size      int64
width          float64
dtype: object

In [43]:
auto_data.corr()

                price  engine-size     width
price        1.000000     0.872335  0.751265
engine-size  0.872335     1.000000  0.729436
width        0.751265     0.729436  1.000000

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = auto_data.drop('price', axis=1)
Y = auto_data['price']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.5, random_state=0)

model = LinearRegression()
model.fit(X_train,Y_train)

print('결정계수(train) : {:.3f}'.format(model.score(X_train,Y_train)))
print('결정계수(test) : {:.3f}'.format(model.score(X_test, Y_test)))
print('\n회귀계수\n{}'.format(pd.Series(model.coef_,index=X.columns)))
print('절편 : {:.3f}'.format(model.intercept_))

결정계수(train) : 0.783
결정계수(test) : 0.778

회귀계수
engine-size     109.526787
width          1261.735518
dtype: float64
절편 : -84060.643